-- ==============================================================================
-- Supabase Schema for Family Movie Ratings
-- ==============================================================================

-- 1. Create Tables
-- ------------------------------------------------------------------------------

-- Table: people
CREATE TABLE IF NOT EXISTS public.people (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: movies
CREATE TABLE IF NOT EXISTS public.movies (
    id bigint generated by default as identity primary key,
    tmdb_id bigint unique,
    title text not null,
    original_title text,
    release_year integer,
    poster_url text,
    overview text,
    average_score numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: scores
CREATE TABLE IF NOT EXISTS public.scores (
    id bigint generated by default as identity primary key,
    movie_id bigint not null references public.movies(id) on delete cascade,
    person_id bigint not null references public.people(id) on delete cascade,
    score numeric not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- Ensure a person can only score a specific movie once
    unique(movie_id, person_id)
);


-- 2. Indexes
-- ------------------------------------------------------------------------------
-- Indexes to improve query performance, especially for foreign keys and common filters
CREATE INDEX IF NOT EXISTS idx_movies_tmdb_id ON public.movies(tmdb_id);
CREATE INDEX IF NOT EXISTS idx_scores_movie_id ON public.scores(movie_id);
CREATE INDEX IF NOT EXISTS idx_scores_person_id ON public.scores(person_id);


-- 3. Row Level Security (RLS)
-- ------------------------------------------------------------------------------
-- Enable RLS on all tables
ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- Since the application uses the Supabase Anon Key without user authentication,
-- we need to create policies that allow public (anon) access to perform all operations (CRUD).
-- NOTE: In a production app with auth, these policies should be restricted to authenticated users.

-- Policies for 'people' table
CREATE POLICY "Allow public all operations on people" 
ON public.people 
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Policies for 'movies' table
CREATE POLICY "Allow public all operations on movies" 
ON public.movies 
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Policies for 'scores' table
CREATE POLICY "Allow public all operations on scores" 
ON public.scores 
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);
